"""
AREX agent configuration manager.
Generates arex.agent.conf content for target JVM processes.
Replaces repeater config_manager — no sandbox HTTP API, no JSON config.
"""
from __future__ import annotations

from dataclasses import dataclass


# Default values used when app-level overrides are absent
_DEFAULT_SAMPLE_RATE = 1.0
_DEFAULT_ENABLE_DEBUG = False


def build_arex_conf(
    app,
    arex_storage_host: str,
    arex_storage_port: int,
) -> str:
    """
    Build arex.agent.conf file content for a target application.

    Args:
        app: Application ORM object (needs .name, .sample_rate attributes).
        arex_storage_host: Hostname/IP of arex-storage service reachable from the target server.
        arex_storage_port: Port of arex-storage service.

    Returns:
        Multi-line string suitable for writing directly to arex.agent.conf.
    """
    sample_rate = getattr(app, "sample_rate", _DEFAULT_SAMPLE_RATE)
    if sample_rate is None:
        sample_rate = _DEFAULT_SAMPLE_RATE

    lines = [
        f"arex.service.name={app.name}",
        f"arex.storage.service.host={arex_storage_host}:{arex_storage_port}",
        f"arex.enable.debug={'true' if _DEFAULT_ENABLE_DEBUG else 'false'}",
        f"arex.sample.rate={sample_rate:.2f}",
    ]
    return "\n".join(lines) + "\n"


def get_default_conf_preview() -> str:
    """
    Return a human-readable preview of the default arex.agent.conf.
    Used by the UI to show operators what the config looks like before deployment.
    """
    return (
        "# arex.agent.conf — generated by arex-platform\n"
        "arex.service.name=<your-app-name>\n"
        "arex.storage.service.host=<arex-storage-host>:8080\n"
        "arex.enable.debug=false\n"
        "arex.sample.rate=1.00\n"
    )


def parse_arex_storage_url(url: str) -> tuple[str, int]:
    """
    Parse an arex_storage_url like 'http://arex-storage:8080' into (host, port).
    Falls back to ('localhost', 8080) on parse failure.
    """
    try:
        # Strip scheme
        without_scheme = url.split("://", 1)[-1].rstrip("/")
        if ":" in without_scheme:
            host, port_str = without_scheme.rsplit(":", 1)
            return host, int(port_str)
        return without_scheme, 8080
    except (ValueError, IndexError):
        return "localhost", 8080
